spring:
  application:
    name: code_brew

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create  # 테스트 시 테이블을 먼저 생성함
    show-sql: true
    defer-datasource-initialization: true # 중요: Hibernate가 테이블을 만든 후 data.sql을 실행하게 함
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always # data.sql 파일을 읽어서 실행하도록 설정

springdoc:
  default-produces-media-type: application/json; charset=UTF-8

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE


